mecanum_odometry:
  ros__parameters:

    # 휠 직경 152 mm → 반지름 76 mm
    wheel_radius: 0.076

    # 앞뒤 휠 중심 사이 전체 거리
    wheelbase_x: 0.380

    # 좌우 휠 중심 사이 전체 거리
    wheelbase_y: 0.330

    # 입력 배열 순서:
    # [앞왼쪽 FL, 앞오른쪽 FR, 뒤왼쪽 RL, 뒤오른쪽 RR]
    wheel_state_topic: "/wheel_states"

    odom_topic: "/odom"

    odom_frame: "odom"
    base_frame: "base_footprint"

    # 실제 모터 원시 속도 부호
    # FL: ID 2, +
    # FR: ID 1, -
    # RL: ID 4, +
    # RR: ID 3, -
    front_left_sign: 1.0
    front_right_sign: -1.0
    rear_left_sign: 1.0
    rear_right_sign: -1.0

    publish_tf: true

    update_rate: 50.0
    wheel_data_timeout: 0.2
    wheel_velocity_deadband: 0.02

    minimum_dt: 0.001
    maximum_dt: 0.1

    # 실차 보정 전 초기값
    linear_x_scale: 1.0
    linear_y_scale: 1.0
    angular_z_scale: 1.0

    initial_x: 0.0
    initial_y: 0.0
    initial_yaw: 0.0
