<?xml version="1.0"?>
<package format="3">
  <name>agv_control</name>
  <version>0.1.0</version>
  <description>Convert cmd_vel into fixed-order mecanum wheel commands.</description>
  <maintainer email="256262348+SEOLA-CHO@users.noreply.github.com">SEOLA CHO</maintainer>
  <license>Apache-2.0</license>

  <depend>agv_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_srvs</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
